stages:
  - build

java-build:
  # select the most appropriate image for your project
  image: maven:3.8-openjdk-11
  stage: build
  variables:
    HOSTNAME: 
    PORT: 
  # before_script:
  script:
    - mvn package -DskipTests=true
    - echo "contents: "
    - ls -la
